name: Cleanup caches

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:      
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          
          echo "Fetching list of cache key"
          cacheKeys=$(gh actions-cache list -R ${{ github.repository }} --key ${{ inputs.name }} -L 100 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R ${{ github.repository }} --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}