name: Restore NPM JS dependencies

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      name:
        required: true
        type: string
      dependencies:
        required: false
        type: string
        default: ''

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        with:
          path: ${{ format('{0}{1}/', inputs.path, 'node_modules') }}
          key: ${{ inputs.name }}-node_modules
  
      - name: Restore dependencies
        run: |
          cd ${{ inputs.path }}
          npm ci
  
      - name: Install internal dependencies
        if: inputs.dependencies != ''
        run: |
          cd ${{ inputs.path }}
          npm i ${{ inputs.dependencies }}

      - name: Save cached dependencies
        uses: actions/cache/save@v3
        with:
          path: ${{ format('{0}{1}/', inputs.path, 'node_modules') }}
          key: ${{ inputs.name }}-node_modules